# -*- coding: utf-8 -*-
"""app

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1cKnmDhcYd1B0k20_ctBRG6dlOq-LEt2b
"""

import streamlit as st
import pandas as pd
import numpy as np
import joblib
from geopy.geocoders import GoogleV3

# Load model
model = joblib.load("model.pkl")

# Initialize geolocator with API key from secrets
geolocator = GoogleV3(api_key=st.secrets["google_maps_api_key"])

st.title("🏡 California House Price Predictor")

# Address input (no default)
address = st.text_input("Property Address")

# Other inputs
sqft = st.number_input("Living Area (sqft)", 500, 10000, step=50)
beds = st.number_input("Bedrooms", 0, 10)
baths = st.number_input("Bathrooms", 0, 10)
garage_spaces = st.number_input("Garage Spaces", 0, 5)
lot_size = st.number_input("Lot Size (sqft)", 1000, 20000, step=100)
year_built = st.number_input("Year Built", 1900, 2025)
stories = st.selectbox("Stories", [1, 2, 3])
parking_total = st.number_input("Total Parking Spaces", 0, 10)

attached_garage = st.selectbox("Attached Garage", ["No", "Yes"])
fireplace = st.selectbox("Fireplace", ["No", "Yes"])
pool = st.selectbox("Private Pool", ["No", "Yes"])
view = st.selectbox("Has View", ["No", "Yes"])
new_construction = st.selectbox("New Construction", ["No", "Yes"])
location_cluster = st.selectbox("Location Cluster", list(range(1, 20)))

if st.button("Predict Price"):
    if not address:
        st.error("Please enter a property address.")
    else:
        # Geocode the address to get lat/lon
        location = geolocator.geocode(address)
        if location is None:
            st.error("Could not geocode the address. Please enter a valid address.")
        else:
            latitude = location.latitude
            longitude = location.longitude
            st.markdown(f"**Resolved Latitude:** {latitude:.5f}")
            st.markdown(f"**Resolved Longitude:** {longitude:.5f}")

            input_dict = {
                'LivingArea': sqft,
                'BedroomsTotal': beds,
                'BathroomsTotalInteger': baths,
                'GarageSpaces': garage_spaces,
                'LotSizeSquareFeet': lot_size,
                'YearBuilt': year_built,
                'Stories': stories,
                'ParkingTotal': parking_total,
                'Latitude': latitude,
                'Longitude': longitude
            }

            dummy_cols = [
                'AttachedGarageYN_1', 'FireplaceYN_1', 'NewConstructionYN_1',
                'PoolPrivateYN_1', 'ViewYN_1'
            ]
            for col in dummy_cols:
                input_dict[col] = 0

            if attached_garage == "Yes":
                input_dict['AttachedGarageYN_1'] = 1
            if fireplace == "Yes":
                input_dict['FireplaceYN_1'] = 1
            if new_construction == "Yes":
                input_dict['NewConstructionYN_1'] = 1
            if pool == "Yes":
                input_dict['PoolPrivateYN_1'] = 1
            if view == "Yes":
                input_dict['ViewYN_1'] = 1

            for i in range(2, 20):
                col = f'LocationCluster_{float(i)}'
                input_dict[col] = 1 if location_cluster == i else 0

            input_df = pd.DataFrame([input_dict])
            model_features = model.feature_names_in_
            input_df = input_df.reindex(columns=model_features, fill_value=0)

            log_price = model.predict(input_df)[0]
            predicted_price = np.expm1(log_price)

            st.success(f"💰 Estimated Home Price: ${predicted_price:,.0f}")

